---
title: "Philipine_Poirier"
author: "Philipine Poirier"
format: html
---
```{r}
library(readr)
library(dplyr)
library(knitr)
library(ggplot2)
library(lubridate)
library(tidyr)

```


# Question 1 
```{r}
courses <- read_csv("courses.csv")
```

# Question 2 
```{r}
courses %>%
  rename(
    "identifiant" = course_id,
    "semester" = semester,
    "number of exams" = nb_grades
  ) %>%
  arrange(`course`) %>%
  kable()
```


# Question 3 
```{r}
students <- read_csv("students.csv") %>%
  mutate(
    id = as.integer(id),
    group = factor(group),
    birth_date = as.Date(birth_date),
    sex = factor(sex)
  )

class(students$birth_date)
class(students$sex)

```

# Question 4
```{r}
grades <- read_csv("grades.csv")
grades <- read_delim("grades.csv",
  delim = "|",
na = "_",
)

```

# Question 5

```{r}
students %>%
  group_by(group) %>%
  summarise(n_students = n()) %>%
  ggplot(aes(x = group, y = n_students)) +
  geom_col()
```

# Question 6 

```{r}
students %>%
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill")
```

# Question 7 
```{r}
students <- students %>% 
  mutate(
    age = round(time_length(today() - birth_date, unit = "year"))
  )
```

```{r}
students %>%
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1)
```

# Question 8
```{r}
age_group <- students %>%
  group_by(group) %>%
  summarise(median_age = median(age))

kable(age_group)
```

# Question 9 
```{r}
#? 
```

# Question 10
The data set contains `r sum(!is.na(grades$grade))` grades.


# Question 12
```{r}

```

# Question 13
```{r}
nb_grades_student <- grades %>%
  group_by(id) %>%                     
  summarise(nb_grades = n()) %>%
  left_join(students %>% select(id, sex), 
            by = "id") 

nb_grades_student %>%
  slice_head(n = 5) %>%
  knitr::kable()
```

# Question 14
```{r}
nb_grades_student %>%
  ggplot(aes(x = sex, y = nb_grades)) +
  geom_boxplot()
```

# Question 15 

```{r}
herbal <- grades %>%
  filter(course_id == 2)


herbal_nb <- herbal %>%
  group_by(id) %>%
  summarise(nb_grades = sum(!is.na(grade)))

herbal_nb <- herbal_nb %>%
  left_join(students %>% select(id, group, sex),
            by = "id")

herbal_nb %>%
  slice_head(n = 5) %>%
  knitr::kable()
```

# Question 16 
```{r}
herbal_dist <- herbal_nb %>%
  group_by(nb_grades) %>%
  summarise(n_students = n())

herbal_dist %>%
  ggplot(aes(x = nb_grades, y = n_students)) +
  geom_col()
```

# Question 17
```{r}
herbal_nb %>%
  ggplot(aes(x = group, y = nb_grades)) +
  geom_boxplot()
```

# Question 18
```{r}
herbal_nb %>%
  ggplot(aes(x = group, y = nb_grades, fill = sex)) +
  geom_boxplot()
```

# Question 19
```{r}
avg_per_course <- grades %>%
  group_by(id, course_id) %>%
  summarise(avg_grade = mean(grade, na.rm = TRUE))

avg_per_course <- avg_per_course %>%
  left_join(students %>% select(id, group), by = "id")


avg_per_course <- avg_per_course %>%
  left_join(courses %>% select(course_id, `course`),
            by = c("course_id" = "course_id"))

wide_average <- avg_per_course %>%
  mutate(avg_grade = round(avg_grade, 2)) %>%   # <-- arrondi ici
  select(id, group, `course`, avg_grade) %>%
  pivot_wider(
    names_from = `course`,
    values_from = avg_grade
  )


wide_average %>%
  select(id, group,
         `Animal Lore and Totemism`,
         `Astronomy and Celestial Navigation`) %>%
  slice_head(n = 5) %>%
  knitr::kable()
```

# Question 20 
```{r}
wide_average %>%
  ggplot(aes(x = `Storytelling and Oral Tradition`,
             y = `Tribal Law and Customs`)) +
  geom_point()
```
# Question 21
```{r}
correlation <- wide_average %>%
  group_by(group) %>%
  summarise(correlation = cor(`Hunting and Gathering Skills`,
                              `Herbalism and Traditional Medicine`))
```

# Question 22
```{r}
max_corr <- correlation %>%
  filter(abs(correlation) == max(abs(correlation))) %>%
  select(group)
max_corr<- max_corr$group

student_max_corr <- wide_average %>%
  filter(group == max_corr)

student_max_corr %>%
  ggplot(aes(x = `Herbalism and Traditional Medicine`,
             y = `Hunting and Gathering Skills`)) +
  geom_point()
```

# Question 23
```{r}
avg_course_student <- grades %>%
  group_by(id, course_id) %>%
  summarise(avg_grade = mean(grade, na.rm = TRUE))

final <- avg_course_student %>%
  group_by(id) %>%
  summarise(final_grade = mean(avg_grade, na.rm = TRUE))

final <- final %>%
  left_join(students %>% select(id, group, sex), by = "id")

final <- final %>%
  arrange(desc(final_grade))

final %>%
  slice_head(n = 5) %>%
  knitr::kable()
```

# Question 24
```{r}
final %>%
  ggplot(aes(x = group, y = final_grade)) +
  geom_boxplot()
```

# Question 25
```{r}
final %>%
  ggplot(aes(x = group, y = final_grade, fill = sex)) +
  geom_boxplot()
```

# Question 26
```{r}
#add the column for the courses with 2 semesters 
avg_course_student <- avg_course_student %>%
  mutate(semester = ifelse(course_id <= 6, 1, 2))

pass <- avg_course_student %>%
  group_by(id) %>%
  summarise(
    min_course = min(avg_grade),
    sem1 = mean(avg_grade[semester == 1]),
    sem2 = mean(avg_grade[semester == 2])
  ) %>%
  mutate(
    pass = (min_course >= 5) & (sem1 >= 10) & (sem2 >= 10)
  )

pass <- pass %>%
  left_join(final %>% select(id, group, sex, final_grade), by = "id") %>%
  select(id, group, final_grade, pass)

pass %>%
  slice_head(n = 5) %>%
  knitr::kable()
```


# Question 27
```{r}
pass %>%
  filter(pass == FALSE & final_grade >= 10) %>%
  summarise(n = n()) %>%
  kable()
```

# Question 28
```{r}
pass_rate <- pass %>%
  group_by(group) %>%
  summarise(pass_rate = mean(pass == TRUE))

pass_rate %>%
  ggplot(aes(x = group, y = pass_rate)) +
  geom_col()
```

# Question 29
```{r}
fail <- avg_course_student %>%
  filter(avg_grade < 5) %>%
  group_by(course_id) %>%
  summarise(nb_fail = n()) %>%       
  arrange(desc(nb_fail)) 

fail %>%
  slice_head(n = 1) %>%
  kable()
```

# Question 30
